#!/bin/bash
set -euo pipefail

version_default="latest"
wanted_version="${BUILDKITE_PLUGIN_BUILDTOOLS_VERSION:-$version_default}"

current_version=''
test_file=build
buildtools_path="/tmp/buildtools-${wanted_version}"
mkdir -p "${buildtools_path}"

if [[ -z "${BUILDKITE_COMMAND:-}" ]]; then
  echo "No command specified"
  exit 1
fi

if [[ -f "${buildtools_path}/$test_file" ]]; then
    current_version=$("${buildtools_path}/$test_file" --version|cut -f1 -d , | cut -f2 -d \ )
fi

latest_version=$(curl -Ls "https://api.github.com/repos/buildtool/build-tools/releases/latest" | jq -r '.name')
latest_version="${latest_version:1}"

if [[ "${wanted_version}" == "${version_default}" ]]; then
    wanted_version="${latest_version}"
fi

if [[ "${current_version}" != "${wanted_version}" ]]; then
    echo "Downloading buildtools version ${wanted_version}"
    wget -O "${buildtools_path}/buildtools.tgz" "https://github.com/buildtool/build-tools/releases/download/v${wanted_version}/build-tools_${wanted_version}_Linux_x86_64.tar.gz"
    tar -C "${buildtools_path}" -xzf "${buildtools_path}/buildtools.tgz"
fi

if [[ -n "${BUILDKITE_PLUGIN_BUILDTOOLS_CONFIG:-}" ]]; then
    envfile="/tmp/env-${BUILDKITE_JOB_ID}"
    echo "Sourcing env config ${BUILDKITE_PLUGIN_BUILDTOOLS_CONFIG}"
    aws s3 cp "${BUILDKITE_PLUGIN_BUILDTOOLS_CONFIG}" "${envfile}"
    # shellcheck source=/dev/null
    source "${envfile}"
    rm -f "${envfile}"
fi

# shellcheck disable=SC2086
${buildtools_path}/${BUILDKITE_COMMAND}
